//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Coches = new HashSet<Coch>();
            this.Files = new HashSet<File>();
            this.Motos = new HashSet<Moto>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "El {0} debe ser, al menos de  {2} caracteres de largo y máximo de {1}", MinimumLength = 3)]
        [Display(Name = "Usuario")]
        public string user1 { get; set; }
        [Required]
        [StringLength(300, ErrorMessage = "El {0} debe ser, de máximo de {1} caracteres")]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "El {0} debe ser, al menos de  {2} caracteres de largo y máximo de {1}", MinimumLength = 1)]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required]
        [Display(Name = "Confirma Contraseña")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Las contraseñas no coinciden.")]
        public string ConfirmPassword { get; set; }
        [Display(Name = "Descripción Foto")]
        public string nombreFichero { get; set; }
        [Display(Name = "Modificar Foto")]
        public byte[] foto { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coch> Coches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moto> Motos { get; set; }
    }
}
